### PR TITLE
Tweak README.md.

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by XhmikosR** [comment]
Rebased.

**Comment by XhmikosR** [comment]
Updated

**Comment by XhmikosR** [comment]
@dayvson: can you please tag the older releases and just push the tags? At least the last 2-3 ones.

Here's how it will look like https://github.com/mpc-hc/grunt-static-inline/releases/tag/0.1.8

**Comment by dayvson** [comment]
Done

**Comment by XhmikosR** [comment]
Err what's done? You didn't merge this.

**Comment by XhmikosR** [comment]
Let alone that you tagged wrong...

You need to tag from the git client for existent releases...

Anyway, just follow the proper release procedure in the future at least.

**Comment by dayvson** [comment]
I created a tag based on the latests version in the master 
https://github.com/dayvson/grunt-static-inline/releases

I didn't merge this, because we had a feel conflicts and I added other stuff to the documentation along with what you change, so the readme should reflact your changes in this pull request.

**Comment by XhmikosR** [comment]
Well the commit you tagged isn't the one you published on npm. And this is
generally bad. I suggest that you delete the tag and do it properly. I can
do it myself if you give me pull rights.

Also this patch has more changes. It's already rebased and should be
mergeable if you reopen the pull request.

**Comment by dayvson** [comment]
What other changes this patch has that are miningful? 
I agree with you about the release tag. But it is not like a big deal since the npm version that has the real coding and tests are published on NPM and this release only has extras commits about the documentation and the AppVeyor which are not that relevant. But anyway.

**Comment by dayvson** [comment]
Anyway, I will make sure the next releases are properly tagged and published on NPM.

Thanks!

**Comment by XhmikosR** [comment]
https://github.com/dayvson/grunt-static-inline/compare/master...mpc-hc:readme

**Pull request closed without merging**
