### PR TITLE
add CDATA sections for XML/XHTML files

### PR DESCRIPTION
**Pull request by philippsimon**

### CODE REVIEW

**Comment by philippsimon** [comment]
@dayvson, @XhmikosR or @mseeley: Could you please merge my pull request? I would need it for a project and prefer to not point to my fork. Thanks!

**Comment by XhmikosR** [comment]
It's not my project :p

On a side note, you should squash those 2 patches into one.

**Comment by philippsimon** [comment]
Sorry - I only saw that the second most commits were from you ;)

And thanks: I squashed them

**Comment by dayvson** [comment]
Sorry for the delay. Thanks for the PR!

**Comment by philippsimon** [comment]
no problem - thanks for adding it!

**Pull request merged**
