### PR TITLE
Update and tweaks

### PR DESCRIPTION
**Pull request by XhmikosR**
* Update dependencies, drop Node.js < 4 support.
* Use `Boolean` and remove unneeded escape.
* Fix HTML validation errors.
* use https
* Tweak CI configs

The datauri update fixes 2 security issues.

The release after this gets merged should be a major version bump due to the Node.js version change.

### CODE REVIEW

**Comment by XhmikosR** [comment]
I added one small patch, everything should be good to go :)

**Comment by XhmikosR** [comment]
One thing I'm not sure if you want is make Node.js 6 the minimum supported version since 4 is unsupported.

**Comment by XhmikosR** [comment]
Friendly ping @dayvson

**Comment by dayvson** [comment]
Looks good to me. Thank you!

**Comment by XhmikosR** [comment]
@dayvson: thanks! Can you also release a new (major) version?

**Pull request merged**
